//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOperater.OperaterServis {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="status", Namespace="http://schemas.datacontract.org/2004/07/ProjectServer")]
    public enum status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        nijeStigaoNaRed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        popravljaSe = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        popravljen = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperaterServis.IOperaterServis", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IOperaterServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/Login", ReplyAction="http://tempuri.org/IOperaterServis/LoginResponse")]
        bool Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/Login", ReplyAction="http://tempuri.org/IOperaterServis/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/proveriLogin", ReplyAction="http://tempuri.org/IOperaterServis/proveriLoginResponse")]
        bool proveriLogin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/proveriLogin", ReplyAction="http://tempuri.org/IOperaterServis/proveriLoginResponse")]
        System.Threading.Tasks.Task<bool> proveriLoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/SumaTroskovaNaAutuZaKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/SumaTroskovaNaAutuZaKorisnikaResponse")]
        double SumaTroskovaNaAutuZaKorisnika();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/SumaTroskovaNaAutuZaKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/SumaTroskovaNaAutuZaKorisnikaResponse")]
        System.Threading.Tasks.Task<double> SumaTroskovaNaAutuZaKorisnikaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/StatusPopravkiNaAutu", ReplyAction="http://tempuri.org/IOperaterServis/StatusPopravkiNaAutuResponse")]
        ProjectOperater.OperaterServis.status[] StatusPopravkiNaAutu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/StatusPopravkiNaAutu", ReplyAction="http://tempuri.org/IOperaterServis/StatusPopravkiNaAutuResponse")]
        System.Threading.Tasks.Task<ProjectOperater.OperaterServis.status[]> StatusPopravkiNaAutuAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperaterServisChannel : ProjectOperater.OperaterServis.IOperaterServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperaterServisClient : System.ServiceModel.ClientBase<ProjectOperater.OperaterServis.IOperaterServis>, ProjectOperater.OperaterServis.IOperaterServis {
        
        public OperaterServisClient() {
        }
        
        public OperaterServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperaterServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperaterServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperaterServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public bool proveriLogin() {
            return base.Channel.proveriLogin();
        }
        
        public System.Threading.Tasks.Task<bool> proveriLoginAsync() {
            return base.Channel.proveriLoginAsync();
        }
        
        public double SumaTroskovaNaAutuZaKorisnika() {
            return base.Channel.SumaTroskovaNaAutuZaKorisnika();
        }
        
        public System.Threading.Tasks.Task<double> SumaTroskovaNaAutuZaKorisnikaAsync() {
            return base.Channel.SumaTroskovaNaAutuZaKorisnikaAsync();
        }
        
        public ProjectOperater.OperaterServis.status[] StatusPopravkiNaAutu() {
            return base.Channel.StatusPopravkiNaAutu();
        }
        
        public System.Threading.Tasks.Task<ProjectOperater.OperaterServis.status[]> StatusPopravkiNaAutuAsync() {
            return base.Channel.StatusPopravkiNaAutuAsync();
        }
    }
}
