//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOperater.OperaterServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaDeo", Namespace="http://schemas.datacontract.org/2004/07/", ItemName="Deo")]
    [System.SerializableAttribute()]
    public class ListaDeo : System.Collections.Generic.List<ProjectLibrary.Deo> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OperaterServis.IOperaterServis", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IOperaterServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/Login", ReplyAction="http://tempuri.org/IOperaterServis/LoginResponse")]
        bool Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/Login", ReplyAction="http://tempuri.org/IOperaterServis/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/proveriLogin", ReplyAction="http://tempuri.org/IOperaterServis/proveriLoginResponse")]
        bool proveriLogin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/proveriLogin", ReplyAction="http://tempuri.org/IOperaterServis/proveriLoginResponse")]
        System.Threading.Tasks.Task<bool> proveriLoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/SumaTroskovaNaAutuZaKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/SumaTroskovaNaAutuZaKorisnikaResponse")]
        double SumaTroskovaNaAutuZaKorisnika();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/SumaTroskovaNaAutuZaKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/SumaTroskovaNaAutuZaKorisnikaResponse")]
        System.Threading.Tasks.Task<double> SumaTroskovaNaAutuZaKorisnikaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/StatusPopravkiNaAutu", ReplyAction="http://tempuri.org/IOperaterServis/StatusPopravkiNaAutuResponse")]
        ProjectLibrary.status[] StatusPopravkiNaAutu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/StatusPopravkiNaAutu", ReplyAction="http://tempuri.org/IOperaterServis/StatusPopravkiNaAutuResponse")]
        System.Threading.Tasks.Task<ProjectLibrary.status[]> StatusPopravkiNaAutuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/PovuciDelove", ReplyAction="http://tempuri.org/IOperaterServis/PovuciDeloveResponse")]
        ProjectOperater.OperaterServis.ListaDeo PovuciDelove();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/PovuciDelove", ReplyAction="http://tempuri.org/IOperaterServis/PovuciDeloveResponse")]
        System.Threading.Tasks.Task<ProjectOperater.OperaterServis.ListaDeo> PovuciDeloveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/PromeniCenuZaIDOdDeo", ReplyAction="http://tempuri.org/IOperaterServis/PromeniCenuZaIDOdDeoResponse")]
        bool PromeniCenuZaIDOdDeo(int ID, double Cena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/PromeniCenuZaIDOdDeo", ReplyAction="http://tempuri.org/IOperaterServis/PromeniCenuZaIDOdDeoResponse")]
        System.Threading.Tasks.Task<bool> PromeniCenuZaIDOdDeoAsync(int ID, double Cena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/PovuciKorisnike", ReplyAction="http://tempuri.org/IOperaterServis/PovuciKorisnikeResponse")]
        ProjectLibrary.Korisnik[] PovuciKorisnike();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/PovuciKorisnike", ReplyAction="http://tempuri.org/IOperaterServis/PovuciKorisnikeResponse")]
        System.Threading.Tasks.Task<ProjectLibrary.Korisnik[]> PovuciKorisnikeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/DodajKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/DodajKorisnikaResponse")]
        bool DodajKorisnika(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/DodajKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/DodajKorisnikaResponse")]
        System.Threading.Tasks.Task<bool> DodajKorisnikaAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/ObrisiKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/ObrisiKorisnikaResponse")]
        bool ObrisiKorisnika(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/ObrisiKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/ObrisiKorisnikaResponse")]
        System.Threading.Tasks.Task<bool> ObrisiKorisnikaAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/PromeniUserNameKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/PromeniUserNameKorisnikaResponse")]
        bool PromeniUserNameKorisnika(string newUserName, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/PromeniUserNameKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/PromeniUserNameKorisnikaResponse")]
        System.Threading.Tasks.Task<bool> PromeniUserNameKorisnikaAsync(string newUserName, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/DodajAutomobilZaKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/DodajAutomobilZaKorisnikaResponse")]
        bool DodajAutomobilZaKorisnika(string userName, string naziv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/DodajAutomobilZaKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/DodajAutomobilZaKorisnikaResponse")]
        System.Threading.Tasks.Task<bool> DodajAutomobilZaKorisnikaAsync(string userName, string naziv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/ObrisiAutomobilZaKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/ObrisiAutomobilZaKorisnikaResponse")]
        bool ObrisiAutomobilZaKorisnika(string userName, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOperaterServis/ObrisiAutomobilZaKorisnika", ReplyAction="http://tempuri.org/IOperaterServis/ObrisiAutomobilZaKorisnikaResponse")]
        System.Threading.Tasks.Task<bool> ObrisiAutomobilZaKorisnikaAsync(string userName, int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOperaterServisChannel : ProjectOperater.OperaterServis.IOperaterServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperaterServisClient : System.ServiceModel.ClientBase<ProjectOperater.OperaterServis.IOperaterServis>, ProjectOperater.OperaterServis.IOperaterServis {
        
        public OperaterServisClient() {
        }
        
        public OperaterServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperaterServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperaterServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperaterServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
        
        public bool proveriLogin() {
            return base.Channel.proveriLogin();
        }
        
        public System.Threading.Tasks.Task<bool> proveriLoginAsync() {
            return base.Channel.proveriLoginAsync();
        }
        
        public double SumaTroskovaNaAutuZaKorisnika() {
            return base.Channel.SumaTroskovaNaAutuZaKorisnika();
        }
        
        public System.Threading.Tasks.Task<double> SumaTroskovaNaAutuZaKorisnikaAsync() {
            return base.Channel.SumaTroskovaNaAutuZaKorisnikaAsync();
        }
        
        public ProjectLibrary.status[] StatusPopravkiNaAutu() {
            return base.Channel.StatusPopravkiNaAutu();
        }
        
        public System.Threading.Tasks.Task<ProjectLibrary.status[]> StatusPopravkiNaAutuAsync() {
            return base.Channel.StatusPopravkiNaAutuAsync();
        }
        
        public ProjectOperater.OperaterServis.ListaDeo PovuciDelove() {
            return base.Channel.PovuciDelove();
        }
        
        public System.Threading.Tasks.Task<ProjectOperater.OperaterServis.ListaDeo> PovuciDeloveAsync() {
            return base.Channel.PovuciDeloveAsync();
        }
        
        public bool PromeniCenuZaIDOdDeo(int ID, double Cena) {
            return base.Channel.PromeniCenuZaIDOdDeo(ID, Cena);
        }
        
        public System.Threading.Tasks.Task<bool> PromeniCenuZaIDOdDeoAsync(int ID, double Cena) {
            return base.Channel.PromeniCenuZaIDOdDeoAsync(ID, Cena);
        }
        
        public ProjectLibrary.Korisnik[] PovuciKorisnike() {
            return base.Channel.PovuciKorisnike();
        }
        
        public System.Threading.Tasks.Task<ProjectLibrary.Korisnik[]> PovuciKorisnikeAsync() {
            return base.Channel.PovuciKorisnikeAsync();
        }
        
        public bool DodajKorisnika(string userName, string password) {
            return base.Channel.DodajKorisnika(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> DodajKorisnikaAsync(string userName, string password) {
            return base.Channel.DodajKorisnikaAsync(userName, password);
        }
        
        public bool ObrisiKorisnika(string userName) {
            return base.Channel.ObrisiKorisnika(userName);
        }
        
        public System.Threading.Tasks.Task<bool> ObrisiKorisnikaAsync(string userName) {
            return base.Channel.ObrisiKorisnikaAsync(userName);
        }
        
        public bool PromeniUserNameKorisnika(string newUserName, string userName) {
            return base.Channel.PromeniUserNameKorisnika(newUserName, userName);
        }
        
        public System.Threading.Tasks.Task<bool> PromeniUserNameKorisnikaAsync(string newUserName, string userName) {
            return base.Channel.PromeniUserNameKorisnikaAsync(newUserName, userName);
        }
        
        public bool DodajAutomobilZaKorisnika(string userName, string naziv) {
            return base.Channel.DodajAutomobilZaKorisnika(userName, naziv);
        }
        
        public System.Threading.Tasks.Task<bool> DodajAutomobilZaKorisnikaAsync(string userName, string naziv) {
            return base.Channel.DodajAutomobilZaKorisnikaAsync(userName, naziv);
        }
        
        public bool ObrisiAutomobilZaKorisnika(string userName, int id) {
            return base.Channel.ObrisiAutomobilZaKorisnika(userName, id);
        }
        
        public System.Threading.Tasks.Task<bool> ObrisiAutomobilZaKorisnikaAsync(string userName, int id) {
            return base.Channel.ObrisiAutomobilZaKorisnikaAsync(userName, id);
        }
    }
}
